FROM python:3.10-slim

# Video işleme motoru (FFmpeg) ve gerekli alt bağımlılıkları sisteme kuruyoruz
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsm6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Servisimizin portunu ve başlangıç komutunu netleştiriyoruz
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8089"]
